version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    expose:
      - "8501"
    environment:
      - GEMINI_API_KEY=AIzaSyAovyixGE4tBbvr2_raLWE6bcyplFC3IHM
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=SRA
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SRA
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
